//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::agreement::Entity as Agreement;
pub use super::agreement_acceptance_status::Entity as AgreementAcceptanceStatus;
pub use super::agreement_versions::Entity as AgreementVersions;
